sudo: required
services:
  - docker
install:
  - docker pull texnical/tl-stretch
  - touch resume.pdf
script:
  - ls -halF
  - docker run -d -v "$(pwd)/resume.tex:/resume.tex" -v "$(pwd)/resume.pdf:/resume.pdf" texnical/tl-stretch pdflatex resume.tex
  - ls -halF
before_deploy:
  - mv resume.pdf latest.pdf
deploy:
  provider: pages
  name: "Mark Smullen"
  email: "marksmullen@letu.edu"
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  file:
    - latest.pdf
  on:
    branch: master
