sudo: required
services:
  - docker
before_install:
  - docker pull texnical/tl-stretch
  - docker run -d -v "$(pwd):~" texnical/tl-stretch pdflatex ~/resume.tex
script:
  - pdflatex ~/resume.tex
before_deploy:
  - mv ~/resume.pdf latest.pdf
deploy:
  provider: pages
  name: "Mark Smullen"
  email: "marksmullen@letu.edu"
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  file:
    - latest.pdf
  on:
    branch: master
