sudo: required
services:
  - docker
install:
  - docker pull texnical/tl-stretch:latest
# - apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
  - docker run -it -v $(pwd)/resume.tex:/resume.tex texnical/tl-stretch:latest sh -c "pdflatex /resume.tex"
before_deploy:
  - mv resume.pdf latest.pdf
deploy:
  provider: pages
  name: "Mark Smullen"
  email: "marksmullen@letu.edu"
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  file:
    - latest.pdf
  on:
    branch: master
